spring.application.name=backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=shop;encrypt=true;trustServerCertificate=true
spring.datasource.username=shopmana
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update

# Thư mục lưu ảnh sản phẩm (tương đối thư mục backend khi chạy mvn)
app.upload.dir=uploads
spring.jpa.show-sql=true